# Generated by Django 5.2.5 on 2025-09-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.FloatField(),
        ),
    ]
