# Generated by Django 5.2.5 on 2025-09-08 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorySubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_subcategories",
                        to="products.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategory_categories",
                        to="products.subcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "subcategory")},
            },
        ),
    ]
