# Generated by Django 5.2.5 on 2025-09-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_categorysubcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Products",
        ),
    ]
