# Generated by Django 5.2.5 on 2025-09-08 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_delete_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_type", models.CharField(max_length=100)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("sell_price", models.FloatField()),
                ("purchase_price", models.FloatField()),
                ("quantity", models.PositiveIntegerField()),
                ("vendor", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("sku", models.CharField(max_length=100, unique=True)),
                (
                    "category_subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.categorysubcategory",
                    ),
                ),
            ],
        ),
    ]
