# Generated by Django 6.0 on 2026-02-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slider/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
