# Generated by Django 6.0 on 2026-02-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="slide_index",
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
