# Generated by Django 6.0 on 2026-02-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_slider_slide_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="slide_index",
            field=models.IntegerField(unique=True),
        ),
    ]
