# Generated by Django 6.0 on 2026-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_slider_slide_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="link",
            field=models.CharField(default="/allproducts", max_length=500),
        ),
    ]
