# Generated by Django 6.0 on 2026-02-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_slider_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
