# Generated by Django 6.0 on 2026-02-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_slider_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "announcement_text",
                    models.CharField(
                        default="Explore a new drop of chic fits here", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
