# Generated by Django 6.0 on 2026-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="is_scrolling",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="announcement_text",
            field=models.CharField(max_length=255),
        ),
    ]
