# Generated by Django 6.0 on 2026-02-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_sitesettings_is_scrolling_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Percentage of discount to be applied (e.g., 10 for 10%).",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="is_sale_on",
            field=models.BooleanField(
                default=False,
                help_text="Enable this to display the product in the Sale section and apply the discount.",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="original_price",
            field=models.FloatField(
                default=100,
                help_text="The actual price of the product before any discount.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="products",
            name="sell_price",
            field=models.FloatField(editable=False),
        ),
    ]
