# Generated by Django 6.0 on 2026-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_products_discount_percentage_products_is_sale_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="brand",
            field=models.CharField(
                choices=[
                    ("ALLYS", "Ally's"),
                    ("HEERAS", "Heera's"),
                    ("RANGRAAZ", "Rangraaz"),
                ],
                default="RANGRAAZ",
                max_length=20,
            ),
        ),
    ]
