# Generated by Django 6.0 on 2026-02-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_products_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="category_subcategory",
        ),
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.subcategory",
            ),
        ),
    ]
