# Generated by Django 6.0 on 2026-02-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_remove_products_category_subcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="purchase_price",
        ),
    ]
