# Generated by Django 6.0 on 2026-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_remove_products_purchase_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="brand",
        ),
        migrations.AlterField(
            model_name="products",
            name="discount_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="products",
            name="is_sale_on",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="products",
            name="original_price",
            field=models.FloatField(help_text="The actual price before discount."),
        ),
    ]
