# Generated by Django 6.0 on 2026-02-20 08:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_remove_products_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
