# Generated by Django 6.0 on 2026-02-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_alter_slider_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="image_url",
        ),
    ]
