# Generated by Django 6.0 on 2026-02-20 10:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_remove_products_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
